const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const vm = require('node:vm');
const {zipSync, unzipSync, strToU8, strFromU8} = require('fflate');
const source = fs.readFileSync(require('node:path').join(__dirname, '../src/utils/activityArchive.ts'), 'utf8');
const context = {exports: {}};
vm.runInNewContext(ts.transpileModule(source, {compilerOptions: {module: ts.ModuleKind.CommonJS}}).outputText, context);
const {activityArchiveName, activityArchiveEntry, monthlySubmittedLogs} = context.exports;
const base = {id:'same', userId:'User01', userName:'테스트/동아리', date:'2026-07-02',startTime:'10:00',endTime:'11:00',activityContent:'합주 연습'};
const logs = monthlySubmittedLogs([base, {...base}, {...base,date:'2026-08-02'}, {...base,activityContent:'  '}], '2026-07');
assert.equal(logs.length, 2);
assert.throws(()=>activityArchiveName('all'));
assert.throws(()=>activityArchiveName('2026-13'));
const folder = activityArchiveName('2026-07');
assert.equal(folder,'2026년_7월_청소년동아리_활동일지');
assert.equal(activityArchiveName('2026-07','테스트/동아리'),'2026년_7월_테스트_동아리_활동일지');
const files = Object.fromEntries(logs.map((b,i)=>[`${folder}/${activityArchiveEntry(b,i)}`,strToU8('PDF fixture '+i)]));
assert.equal(Object.keys(files).length,2);
const restored = unzipSync(zipSync(files,{level:0}));
assert.deepEqual(Object.keys(restored),Object.keys(files));
assert.equal(strFromU8(Object.values(restored)[1]),'PDF fixture 1');
assert.equal(monthlySubmittedLogs([base],'2026-06').length,0);
console.log('PASS: month boundaries, unsubmitted exclusion, empty month, Korean archive names, unsafe character replacement, duplicate filenames, ZIP round-trip.');
